[PROXY]
EnableProxyLibrary=0
InitProxyFunctions=0
ProxyLibrary
[GLOBAL]
UseEffect=1
AlternativeDepth=1
AllowAntialias=0
BugFixMode=0
SkipShaderOptimization=0
QuadVertexBuffer=0
EnableShaders_3_0=0
AdditionalConfigFile=enbseries2.ini
UseMRTRendering=0
[EFFECT]
EnableBloom=0
EnableOcclusion=0
EnableReflection=0
EnableMotionBlur=0
EnableWater=0
EnableShadow=0
DepthBias=0
EnableDepthOfField=0
[INPUT]
KeyUseEffect=123
KeyBloom=120
KeyOcclusion=129
KeyReflection=122
KeyCombination=16
KeyScreenshot=121
KeyShadow=119
KeyWater=118
KeyShowFPS=106
[REFLECTION]
ReflectionPower=150
ChromePower=100
UseCurrentFrameReflection=1
ReflectionQuality=0
ReflectionSourceSpecular=50
ReflectionSourceTFactor=50
UseAdditiveReflection=1
ReflectionDepthBias=0
UseLowResReflection=0
ReflectionSinglePass=1
UseEnvBump=0
EnvBumpAmount=100
EnvBumpOffset=100
ReflectionFlip=1
[BLOOM]
BloomPowerDay=0
BloomFadeTime=2000
BloomConstantDay=10
BloomQuality=0
BloomScreenLevelDay=0
BloomCurveDay=0
BloomPowerNight=0
BloomConstantNight=10
BloomCurveNight=0
BloomScreenLevelNight=0
BloomAdaptationScreenLevel=0
BloomAdaptationMultiplier=0
BloomAllowOversaturation=1
BloomMaxLimit=100
[SSAO]
UseFilter=0
OcclusionQuality=0
FilterQuality=1
DarkeningLevel=30
BrighteningLevel=30
IlluminationLevel=30
AdditiveIlluminationLevel=30
UseAmbientOcclusion=1
UseIndirectLighting=1
FadeDistance=50
UseForAlphaTest=1
UseForAlphaBlend=1
UseNoiseRandomization=1
[COLORCORRECTION]
DarkeningAmountDay=0
ScreenLevelDay=0
ScreenLevelNight=0
DarkeningAmountNight=0
GammaCurveDay=0
GammaCurveNight=0
ColorSaturationDay=1
ColorSaturationNight=1
UsePaletteTexture=0
[ENGINE]
ForceAnisotropicFiltering=0
MaxAnisotropy=16
ForceDisplayRefreshRate=0
DisplayRefreshRateHz=60
ForceDisplaySize=0
DisplayWidth=1024
DisplayHeight=768

[WATER]
UseWaterDeep=1
WaterDeepness=20
WaterQuality=0
[SHADOW]
ShadowFadeStart=40
ShadowFadeEnd=80
ShadowAmountDay=60
ShadowAmountNight=30
ShadowScreenLevelDay=60
ShadowScreenLevelNight=20
ShadowQuality=0
UseShadowFilter=0
FilterQuality=2
ShadowBlurRange=30
[MOTIONBLUR]
MotionBlurQuality=1
MotionBlurVelocity=40
MotionBlurRotation=40
[PERPIXELLIGHTING]
SpecularColorMin=0
SpecularColorMax=100
SpecularColorMultiplier=100
SpecularGlossinessMin=0
SpecularGlossinessMax=100
SpecularGlossinessMultiplier=100
[DEPTHOFFIELD]
DOFQuality=0
DOFNumberOfPasses=1
DOFFocusRange=50
DOFBlurinessRange=5
DOFFadeTime=1000
DOFFiltered=1
[FIX]
PixelShaderLimit=500
DisableShaders=0
ForceOldDXVersion=1
UseVertexTextureFetch=0
DelayTime=30
ForceAffinityMask=0
